name: Wheels

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-11","ubuntu-22.04"]

    steps:
      - uses: actions/checkout@v4
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.2
        env:
          # CIBW_PRERELEASE_PYTHONS: True
          CIBW_ARCHS_MACOS: x86_64 universal2
      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
